name: Deploy AWS Infra

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up python 
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'

      - name: Install dependency 
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pulumi pulumi-aws
      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-southeast-1
      - name: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}
        run: pulumi login

      - name: pulumi stack select
        run: pulumi stack select TimamBinSaifTahmid/Infra/dev
      
      - name: pulumi up
        run: pulumi up --yes